version: '3.8'

services:
  memory-service:
    build:
      context: ../..
      dockerfile: src/services/memory/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - CHROMA_PERSIST_DIR=/app/chroma
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - USE_VERTEX_AI=false
      # JWT settings (optional - not currently used)
      # - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      # - JWT_ALGORITHM=HS256
      # - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - SHORT_TERM_MEMORY_SIZE=100
      - LONG_TERM_MEMORY_SIZE=1000
      - RELEVANCE_THRESHOLD=0.6
      - STABILITY_THRESHOLD=0.7
      - EXPLICITNESS_THRESHOLD=0.5
      - ENV=development
    volumes:
      - ../../:/app
      - chroma-data:/app/chroma
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  chroma-data: