version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MEMORY_SERVICE_HOST=0.0.0.0
      - MEMORY_SERVICE_PORT=8000
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    env_file:
      - ./frontend/.env.local
    depends_on:
      backend:
        condition: service_healthy

volumes:
  redis_data: 